### ISSUE TITLE
Keys should be intelligently merged within JSON files

### ISSUE THREAD

**Issue by ppodgorsek** [karolis-sh/rollup-plugin-json-merge#6]
If several JSON files contain the same parent keys, the last file wins and no merge happens.

For example:
* `file1.json`:

    ```json
    {
      "cms": {
        "header": "Welcome"
      }
    }
    ```

* `file2.json`:

    ```json
    {
      "cms": {
        "footer": "Goodbye"
      }
    }
    ```

* Rollup configuration:

    ```js
    merge({
      fileName: 'assets/cms.json',
      input: [
        'cms/file1.json',
        'cms/file2.json',
      ],
    })
    ```

This would lead to the following file being generated:

```json
{
  "cms": {
    "footer": "Goodbye"
  }
}
```

**Comment by karolis-sh** [comment]
It seems what you're after is some custom deep merge. You can provide a custom [`merge` option ](https://github.com/karolis-sh/rollup-plugin-json-merge?tab=readme-ov-file#merge) to achieve such behaviour yourself

**Comment by ppodgorsek** [comment]
Wouldn't it be better to have this as the default merge?

**Comment by karolis-sh** [comment]
I think simple merge is a sensible default that caters to the majority of the use cases. Changing that would be a breaking change - I'd like to avoid that.

For your use case, passing down [lodash's deep merge](https://lodash.com/docs/4.17.15#merge) would probably do the trick, e.g.:

```
import merge from 'rollup-plugin-json-merge';
import * as _ from 'lodash';

export default {
  input: 'src/index.js',
  output: {
    dir: 'output',
    format: 'cjs',
  },
  plugins: [
    merge({
      input: ['src/1.json', 'src/2.json'],
      fileName: 'output.json',
      merge: _.merge,
    }),
  ],
};
```

**Comment by ppodgorsek** [comment]
Thank you! Maybe that could be a useful one to put as an example of the `merge` attribute in the README?

**Comment by ppodgorsek** [comment]
For anyone who might need it, the above merge example should be adjusted slightly to avoid the `_.merge` function returning an array of JSON objects:

```js
import jsonMerge from 'rollup-plugin-json-merge';
import _ from 'lodash';

export default {
  input: 'src/index.js',
  output: {
    dir: 'output',
    format: 'cjs',
  },
  plugins: [
    jsonMerge({
      input: ['src/1.json', 'src/2.json'],
      fileName: 'output.json',
      merge: (items) => { return _.merge({}, ...items) },
    }),
  ],
};
```
